package exec

var AllowedCommands = map[string]bool{
	"kubeadm":    true,
	"kubectl":    true,
	"helm":       true,
	"containerd": true,
	"crictl":     true,
	"apt-get":    true,
	"apt":        true,
	"systemctl":  true,
	"modprobe":   true,
	"sysctl":     true,
	"curl":       true,
	"wget":       true,
	"cat":        true,
	"ls":         true,
	"cp":         true,
	"mkdir":      true,
	"chown":      true,
	"chmod":      true,
	"tee":        true,
	"sed":        true,
	"gpg":        true,
	"unzip":      true,
	"tar":        true,
	"journalctl": true,
	"dmesg":      true,
	"ip":         true,
	"ss":         true,
	"whoami":     true,
	"hostname":   true,
	"env":        true,
	"printenv":   true,
	"rm":         true,
	"mv":         true,
	"head":       true,
	"tail":       true,
	"grep":       true,
	"bash":       true,
	"sh":         true,
	"openssl":    true,
	"jq":         true,
	"base64":     true,
	"echo":       true,
	"sleep":      true,
}

func IsAllowed(binary string) bool {
	return AllowedCommands[binary]
}
